# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-12 10:02
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SchoolName', models.CharField(max_length=50)),
                ('Address', models.TextField(max_length=100)),
                ('Details', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
