# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-15 06:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190712_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='School_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('content', models.TextField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='school',
            name='Details',
            field=jsonfield.fields.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='school_post',
            name='school_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_post', to='app.School'),
        ),
    ]
