# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-15 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190715_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school_post',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
