# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-15 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190715_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car_brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BrandName', models.CharField(max_length=20, verbose_name='Car Brand Name')),
                ('customer_service_number', models.IntegerField(max_length=10, verbose_name='customer care number')),
                ('head_quarters', models.CharField(max_length=100)),
                ('CEO', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Car_brand_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_details', jsonfield.fields.JSONField(default={})),
                ('model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_name', to='app.Car_brand')),
            ],
        ),
    ]
