# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-15 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_car_brand_car_brand_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_brand',
            name='CEO',
            field=models.CharField(max_length=30),
        ),
    ]
