# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-15 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190715_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_brand',
            name='customer_service_number',
            field=models.BigIntegerField(verbose_name='customer care number'),
        ),
    ]
